### ISSUE TITLE
Multiple webview window

### ISSUE THREAD

**Issue by webfolderio** [Soundux/webviewpp#1]
Hi,

I am trying to open multiple webview window but Sound WebView::setup() returns **false** if more than webview instance will be created. What might be the problem?

Thanks

```c
#include <iostream>
#include <webview.hpp>

int main()
{
    SounduxWebView webview;
    webview.setup(800, 900);
    webview.setTitle("Example");
    webview.enableDevTools(true);

    // Call me using the dev tools!
    webview.addCallback("testCallback", [](const std::string &someString, int someInt) {
        std::cout << "Got " << someString << " and " << someInt;
        return someInt * 10;
    });
    webview.navigate("https://ddg.gg");
    webview.run();

    SounduxWebView webview2;

    webview2.setup(800, 900); // <- this returns false and app crashes
    webview2.setTitle("Example");
    webview2.enableDevTools(true);

    // Call me using the dev tools!
    webview2.addCallback("testCallback", [](const std::string &someString, int someInt) {
        std::cout << "Got " << someString << " and " << someInt;
        return someInt * 10;
    });
    webview2.navigate("https://ddg.gg");
    webview2.run();


    return 0;
}
```

**Comment by Curve** [comment]
I currently don't support multiple webviews.
I'll look into it

**Comment by Curve** [comment]
This bug seems to be windows related, its not occuring on linux

![image](https://user-images.githubusercontent.com/37805707/115228585-41c75d80-a112-11eb-97c3-8636b47d219f.png)

**Comment by Curve** [comment]
I found out why this happens on windows.
I'll fix it and refactor some of the code before pushing the fix.

![image](https://user-images.githubusercontent.com/37805707/115229803-c666ab80-a113-11eb-9e8d-e322f06a51c5.png)

**Comment by Curve** [comment]
This should now be fixed :smile:  
Just make sure to give the two webview windows a different identifier ^^

**Comment by webfolderio** [comment]
Thanks for the fix. By the way, new source folder structure and new API is excellent. Thanks!
