### ISSUE TITLE
Windows 7 x64 examples/simple Problem 

### ISSUE THREAD

**Issue by diegofazio** [Soundux/webviewpp#4]
Hi, I create the webview-example( examples/main.cc ) fine and when I run it in Windows 7

Error1(Can't find entry point )
SetProcessDpiAwarenessContext .....

The same happend with the Serge version. If I change to older version of DPI API(https://github.com/webview/webview/pull/527), no more Error1 but it ask for some dll missing

Error2(missing dll)

api-ms-win-core-libraryloader-l1-2-0.dll
api-ms-win-core-libraryloader-l 1-2-0.dll

I download those files( x64 ver ) and the new error

Error3
application cannot start correctly 0xc00005

The same happend with Serge version. The problem is that Webview2( microsoft original ) works perfect with windows 7 x64/x32. I test it. Why this happend? Something added to webviewpp/webview has a conflict with win7.
Any Ideas?

Thanks a Lot!

**Comment by Curve** [comment]
It's because we set dpi awareness, I can disable that call for windows 7 but can't  guarantee that everything else works fine as windows 7 is not officially supported by this library other than that I can't think of anything that would cause the problems you mentioned 

Edit: The other problems you mentioned could be caused by the windows implementation library, however I will not replace that

**Comment by Curve** [comment]
[Windows 8.1 Support](https://github.com/Soundux/webviewpp/blob/master/CMakeLists.txt#L3) will also use the old SetDPIAwareness function - I don't want to look into why it fails on windows 7 tho as I don't plan to support Windows 7, sorry

**Comment by diegofazio** [comment]
No problem. I just curious why with pure webview2 works. 
Here you have a simple test program https://github.com/diegofazio/webview2 for win32/win64. It works perfect on win7/8/10 and it use the windows implementation library. There is something in particularly in Zerge and your webview.h that make it does not work. You can compile from cmd and test it.

**Comment by Curve** [comment]
> I just curious why with pure webview2 works.

Makes me curious too, I'll take a look a the repo you provided, maybe I can find out what causes it

**Comment by Curve** [comment]
Sorry I couldn't find out exactly why it happens but by just looking at the code it may be because of the call to `SetProcessDpiAwareness`, as the earliest Windows version that is officially supported on is Windows 8.1, so you may want to comment out the call completely, maybe that works for you?

**Comment by diegofazio** [comment]
windows.cpp - line 51

#if defined(WEBVIEWPP_WINDOWS_8)

//    SetProcessDpiAwareness(PROCESS_SYSTEM_DPI_AWARE); // NOLINT
#else
//    SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE); // NOLINT
#endif

I commented both. And show a black screen but the webview windows does not appear

**Comment by Curve** [comment]
> I commented both. And show a black screen but the webview windows does not appear

That's weird, then there seems to be another issue on windows 7 because the not setting DPI awareness should not break things
